# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

      # Checkout the repo
      - uses: actions/checkout@v2

      # enable node version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      # Install deps
      - name: Install Deps
        run: yarn
      
      # Build the project
      - name: Build
        env:
          APP_BASE_URL: /asl-client-ml-tutorial/
        run: yarn build
      
      # Copy files
      - name: Copy Files
        run: |
          cp "${GITHUB_WORKSPACE}/dist/index/index.html" "${GITHUB_WORKSPACE}/dist/index.html"

      # deploy to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3

        # only run on push to main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist